### ISSUE TITLE
Limit OC project membership  & populate groups thru

### ISSUE THREAD

**Issue by guillebianco** [opendevstack/ods-project-quickstarters#112]
When a new project in deployed in openshift, all system-authenticated users have view and edit rights.
Can it be changed in future releases?

**Comment by clemensutschig** [comment]
https://github.com/opendevstack/ods-project-quickstarters/blob/master/ocp-templates/scripts/create-projects.sh#L86 ff

**Comment by clemensutschig** [comment]
ok - I did some research finally 
a newly provisioned jenkins master runs as `system:serviceaccount:cleke-cd:jenkins` 

BUT - the slave (that does oc patch!) & build runs as `system:serviceaccount:cleke-cd:default`

this is what https://github.com/opendevstack/ods-project-quickstarters/blob/master/ocp-templates/scripts/create-projects.sh#L69 -> 73 is about .. @michaelsauter - shared lib bug?!

https://github.com/opendevstack/ods-project-quickstarters/blob/master/ocp-templates/scripts/create-projects.sh#L75 -> 76 is ok (pull images from /cd/ project)

https://github.com/opendevstack/ods-project-quickstarters/blob/master/ocp-templates/scripts/create-projects.sh#L77 is again based on the above (:default) user .. :(

https://github.com/opendevstack/ods-project-quickstarters/blob/master/ocp-templates/scripts/create-projects.sh#L86 -> 91 is what @stephenkehoe  / @guillebianco are concerned about .. but
 - as long as we don't have email based login on premise - seeding a project with an admin user (email) that does not work (email vs. short upn) does not really make sense - because no-one has access then?

**Comment by michaelsauter** [comment]
@clemensutschig So what you are saying is that you would want the build to run as the `jenkins` serviceaccount? This could indeed be possible, the `podTemplate` object of https://github.com/jenkinsci/kubernetes-plugin has a `serviceAccount` property ...

The shared lib already allows to customize it, e.g. we can try with the following (instead of the `image` declaration):
```groovy
podContainers: [
    containerTemplate(
      name: 'jnlp',
      image: "${dockerRegistry}/cd/jenkins-slave-maven",
      workingDir: '/tmp',
      alwaysPullImage: true,
      args: '${computer.jnlpmac} ${computer.name}',
      serviceAccount: 'jenkins'
    )
]
```

We can make this the default going forward?! It seems that the current OpenShift default is to start the pod using the `default` service account. Not sure if there is a reason behind not using `jenkins`?

On an unrelated note, Github allows to highlight ranges - e.g. 
https://github.com/opendevstack/ods-project-quickstarters/blob/master/ocp-templates/scripts/create-projects.sh#L86-L91

**Comment by clemensutschig** [comment]
@michaelsauter  - I think we should have jenkins everywhere - to tighten role bindings .. which is on my list for a year+ now :)

**Comment by clemensutschig** [comment]
one more
https://github.com/opendevstack/ods-project-quickstarters/blob/master/ocp-templates/scripts/import_ocp_project_metadata.sh#L344
