### ISSUE TITLE
fe-angular quickstarter fails build with node_modules/rxjs/internal/types.d.ts(81,44): error TS1005: ';'

### ISSUE THREAD

**Issue by torstenhe** [opendevstack/ods-project-quickstarters#129]
Jenkins build / yarn fails with

node_modules/rxjs/internal/types.d.ts(81,44): error TS1005: ';' expected. node_modules/rxjs/internal/types.d.ts(81,74): error TS1005: ';' expected. node_modules/rxjs/internal/types.d.ts(81,77): error TS1109: Expression expected.  

there is already a fix available
see https://github.com/ReactiveX/rxjs/issues/4512

**Comment by clemensutschig** [comment]
The fix is a package.json change to typescript 2.8

**Comment by cschweikert** [comment]
There is not much we can do about this, since the quickstarter for Angular creates the content of a new repository by running `ng new`. This will also create a `package.json` file with the problematic version of typescript. As possible solution I would recommend an update of the Angular version on the quickstarter.
Possible workarounds for now:
* update typescript manually to version 2.8
* run `ng update`

**Comment by clemensutschig** [comment]
Sed replace - done ;-)

**Comment by cschweikert** [comment]
fixed in master and 1.0.x

**Comment by cschweikert** [comment]
Oh, actually there is no typescript version 2.8.0 :-( Why? Anyways.
I reopen the ticket and will change to 2.8.1, which indeed is existing.

**Comment by cschweikert** [comment]
updated to 2.8.1 on master and 1.0.x
