### ISSUE TITLE
Rework quickstarter concept

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-project-quickstarters#254]
To consolidate existing issues, I'm creating a new issue here.

We want to redo the quickstarter concept. So far, the following goals have been distilled:

1. Replace Rundeck with (Jenkins) pipelines. This reduces the number of used software, and Rundeck was always a pain (separate install, difficult to keep in sync with Github, difficult to understand and change). This has been suggested in https://github.com/opendevstack/ods-project-quickstarters/issues/68#issuecomment-474296795. The full issue tracking this is at #283.

2. Allow multiple quickstarter repos. The main use-case for this is to have a "private" repo only in BitBucket, and a public one in GitHub. However, it does not need to be limited to those. See #286. As a first draft, this feature might only be available for advanced users, see CURL request idea in #283.

3. More flexibility within the quickstarters. Right now they assume that everything has the same OpenShift resources etc. See #286. The Jenkinsfiles created as part of #283 will need to address this.

4. Testable quickstarters. Probably the most important requirement - we finally need CI for quickstarters to make them less brittle

5. Contributing to quickstarters should be easy. Right now it is difficult to understand where to make changes, and it is very hard to experiment and test the changes made

6. Proper templating. So far we use `sed` to replace strings, we should have a proper templating language to render e.g. `Jenkinsfile` and `sonar-project.properties`. See #287.

7. "Common interface" to each quickstarter. E.g. a `Makefile` with standardized targets like `build`, `image`, `deploy`, `test` etc ... That way all QS can be interacted with in a standard fashion, which should enable orchestration of releases of multiple repos ...

8. (Potentially) handle common dependencies of quickstarters (e.g. build images, slaves, ...). Right now each quickstarter assumes that e.g. the Jenkins slave magically exists. If we want to have a dynamic number of quickstarte (repos), we probably need some "register"/"install" function to make sure a quickstarter can be used. See #288.

9. (Potentially) allow to pass options to quickstartes when provisioning them, see #211.

10. Move quickstarter-unrelated things to ods-core, see #1, #2, #3 

11. Do not store OCP templates in OpenShift, but rather use the files in the repo to apply them with Tailor. See #38.

12. Deliver OpenShift templates/config with the created repository (and do not create the OCP resources while provisioning, but as a step in the Jenkins pipeline). See #60.

FYI @clemensutschig @hugowschneider @metmajer @rattermeyer @henrjk @stitakis Please review those goals and let me know if you agree on those as (preliminary) scope for the 2.0 quickstarters.

**Comment by henrjk** [comment]
Regarding

> 4. Testable quickstarters. Probably the most important requirement - we finally need CI for quickstarters to make them less brittle

The way one can currently tests a new quickstarter from the provision app manually is way too painful. Some of the issues were described in this [comment](https://github.com/opendevstack/ods-project-quickstarters/issues/38#issuecomment-499946943).  I would want to be able to also make manual testing much easier. Perhaps simply by telling the Provisioning app where to find the quickstarter. Of course CI/CD is also needed so that refactorings don't break existing quickstarters.

So I see several testing requirements:
- Testable quickstarters. Make it easy to test quickstarters under development end to end. 
- Have CI/CD  in place to: 
   - validates that ods owned quickstarters are not broken
   - so that external quickstarters are not broken unintended.

**Comment by metmajer** [comment]
I would like to bring a different view on quickstarter provisioning into the discussion: as a developer, I'd love to be able to just go into a directory and do the following to handle the bootstrapping of a quickstarter into my project.

```
ods project $MY_PROJECT
ods quickstarter new <name> --type=java
```

Where `MY_PROJECT` is a name that references a project in BitBucket and the quickstarter's `name` argument references the variable name part of a repository inside this project. (Technically speaking, the CLI would reference a (Go?) library that implements the provisioning process.) This indirection to our current way of provisioning would provide the following benefits:

1) paves the way for arbitrary project structures and mono-repos (we could get rid of the restriction of 1 quickstarter = 1 Repo)
2) allows CLI, REST API and Web UI to be thin layers on top of a central and teste library
3) easily integrates into anything scripted, e.g., from pipelines to live demos
4) subsequently opens up the provisioner to support custom-built quickstarters (if we support a `--url` next to  `--type`), so that teams do not depend on upstream quickstarters alone

**Comment by metmajer** [comment]
As an additional point, and in line with 9), it would be beneficial to support arbitrary branching strategies to be configured into the quickstarter. Why? Because the branching strategy is a reflection of how developers manage code and we shouldn't expect everyone to be comfortable with Gitflow.

**Comment by metmajer** [comment]
Also, I would like to see documentation vastly improved and build community content that allows users of ODS to get started quickly.

**Comment by michaelsauter** [comment]
@metmajer Regarding "branching strategy": quickstarters do not dictate gitflow right now, in fact it isn't even the default. Developers are free to come up with their own branch-to-environment mapping in the `Jenkinsfile` (see https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/README.md#workflow). Does the current solution sound fine to you or would you want sth else? 

Also, I really really like the CLI idea! However, I see two major downsides of running a CLI locally:

1. We need to create a webhook in BitBucket, to enable automatic builds on push. Doing this via the CLI requires the user to authenticate to BitBucket
2. Right now, the dependencies required for each quickstarter to create the source files are located in the base-slaves used by Rundeck. If the CLI runs locally, each user needs to have the dependencies installed locally. This sounds both more cumbersome and more brittle then the current approach.

I have not found a satisfying answer to those two problems, but maybe you have ideas? I'd love to have what you describe :)

**Comment by tjaeschke** [comment]
> 1. paves the way for arbitrary project structures and mono-repos (we could get rid of the restriction of 1 quickstarter = 1 Repo)

@metmajer What do you mean with arbitrary project structures?  

Just to mention it. It was and as far as I know it still a core paradigm of the ODS that the setup for a project defined by a quickstarter is unified to satisfy business, compliance and security needs out-of-the-box and to ease developer transisitions between projects.
Depending on how arbitrary project structure is meant, it contradicts the paradigm.

And just another question:
Which restriction do you mean? Do you mean, the current restriction, that there is only one quicktarter repo defined?

I like the idea of a CLI implementation, we should discuss this in the open office hours.

**Comment by clemensutschig** [comment]
Whatever we go for seed to be NOT Lust Developer centric but easy to use as
the prov App todayeuch enables 100+ users every day..  One repo One
component makes also defaulting over configuration very real...

Torsten Jaeschke <notifications@github.com> schrieb am Fr., 28. Juni 2019,
21:26:

**Comment by metmajer** [comment]
@michaelsauter happy you like the idea, too!

Here's a thought on how we could address those limitations: instead of having a fully local CLI, the CLI would be merely a client to a corresponding, RESTful web service that handles authentication and quickstarter-specific dependency management through Rundeck (or its successor). How do you manage authentication between the Provisioner App and BitBucket today? Depending on the authentication scenario, a single `ods login` might be achievable.

Thinking of impact vs. effort: it would already be super cool if the following snippet would simply create a repository in BitBucket based on the provided quickstarter type or URL. That means that the user would still have to clone the newly created repository into the workspace manually:

```
ods project $MY_PROJECT
ods quickstarter new <name> [--type|--url]
```

**Comment by metmajer** [comment]
@tjaeschke with "arbitrary project structures" I am referring to giving freedom to developers when it comes to structuring an application across a single (mono-repo) versus multiple repositories. Currently, ODS mandates one repository for each component and hence does not support mono-repos. Here is why I think we need to reconsider.

When a `git push` for a change in a single component automatically leads to the execution of the component's Jenkins pipeline through the Webhook Proxy, then a change that spans more than one repository cannot be `git push`ed and released at once (atomically), and leads to intermittently failing components and experiences by design:

1) In a classical 3-tier architecture, a change in the backend is `git push`ed and released, and subsequently causes errors in the frontend until the frontend itself gets updated.

2) As a best practice, a change in one component should trigger integration tests for all components that depend on this component, and vice versa. However, a `git push` for a breaking change in the backend will cause tests for the frontend to fail, e.g., if the API contract between those two is violated. Generally speaking, as the number of services increase, the more efforts developers will have to put into releasing components in the right order (depending on the change). If the interdependence between some set of services shows a cyclic pattern, this problem is further aggravated.

Technically, some issues can be solved through the application of REST API versioning, circuit breakers, and other patterns of defensive programming, but these only deal with the symptoms. Actually, you don't want to depend on such practices, especially in the beginning, and instead rapidly prototype away to find customer value. Great tooling always supports a developer's way of working and avoids getting in the way. The introduction of unnecessary complexity causes frustration, which in turn is a primary cause for technical debt.

I understand that the current design is based on solid considerations. Besides the above reasoning, to me, forcing developers into managing the complexities of juggling multiple repositories from the beginning contradicts with the O in ODS. (This is also an open source project and we're not solely building it for us and experts only ;-)

**Comment by michaelsauter** [comment]
@metmajer Yup something like this could work. I just wanted to outline some of the complexity involved, because when you first presented the idea I did not see that downside immediately. Maybe a service like the following would work:

1. Based on a URL/quickstarter type, create a repo in BitBucket with the webhook
2. Generate the files to be placed in that repo
3. If invoked from CLI, do NOT push the files to BitBucket but rather download the files to where the CLI was invoked from. If invoked from the prov-app, push the files to BitBucket.

Additionally, the CLI could have a flag to disable step 1, in order to place files in an already existing repo ...

**Comment by stitakis** [comment]
@all, excellent ideas, all of them... however I think we need to discuss of roadmap 2.0 very carefully to create a solid ground for version 2.0... atm... I have the impression that big part of the effort goes into fixing things that we break when introducing new features... for that reason: CI/CD for ODS should be in imho first thing to put in place... secondly, we have a couple of security requirements that need to be addressed by end of 2019... having said that... @michaelsauter as answer for the scope question that you asked... I think any feature related to quickstarters that would simplify CI/CD and/or improve security are good candidates to be included in 2.0

**Comment by michaelsauter** [comment]
@stitakis Did you read my list? Number 4 addresses this, I even added "Probably the most important requirement" :)

**Comment by stitakis** [comment]
@michaelsauter of course I read it... good stuff! :)

**Comment by metmajer** [comment]
@michaelsauter Love the suggestion, but I assume that support for arbitrary repository structures (not just their creation) will require some broader considerations to be made. I'd love to have a quick discussion with you to understand how far reaching a task this would be and how this fits into our upcoming and existing solutions. (Not meaning to exclude anyone here, but GitHub comments only take you so far.)

Here's to recap and slightly adapt your suggestion:

1) `ods quickstarter new <name> ...` calls the web service. The web service creates a BitBucket repo including all required files for the user to get started.
2) The CLI `git clone`s the created repo into a subdirectory `name` underneath the current directory unless the user specifies a `--directory` option to override the default behavior. Once we know what it takes to support arbitrarily structured projects, we could introduce further (optional) options to control how to integrate the new component into the workspace next to `git clone`, such as Git Submodules to reference, develop, and deliver components from within a single repository.

I'd see the above solution as a lean approach, with the possibility to add more complexity on top as we have time and resources. Nevertheless, I can't image we'll continue to live on the 1 component = 1 repo for long because of the above-mentioned side effects. The farther we can get, the better, and I'd be happy to provide additional support.

**Comment by metmajer** [comment]
@michaelsauter to the other discussion point on a "branching strategy" in quickstarters, I should have had a closer look before posting. Thanks for the pointer and being open for alternatives.

Right now, the `branchToEnvironmentMapping` is part of the pipeline implementation. Do we want to make this and other user-configurable aspects part of a central place, such as a `/.pipeline-config.yml`?

Aside from offering a central entry-point to adapting the behaviour of an application component, we already make use of the `.pipeline-config.yml` to communicate capabilities to an upcoming multi-repo orchestration pipeline that is currently being developed. Here are some examples:

### Example: Repo Dependencies

Here, a repository exposes its dependencies on other repositories. This information will allow the orchestration pipeline to derive an execution plan from a dependency graph to build, deploy, test, and release an application's components into a live application in the correct order:

```
dependencies:
  - github.com/getcloudnative/B
  - github.com/opendevstack/C
```

### Example: Pipeline Phases

Continuous Delivery pipelines can be reduced to a build, deploy, test and release process of phases. The following contract describes how these phases map to capabilities provided by the component. This will be a perfect fit to what's denoted under your point 7).

```
phases:
  build:
    tasks: [ build, unit-tests ]
    type: Makefile
  deploy:
    command: oc deploy --latest dc/A
    type: ShellScript
  ...
```

### Example: Dependency Injection

The following example shows a contract that demands the pipeline to provide a set of environment variables. If those are unknown to the pipeline and can thus not be provided, the pipeline should fail.

```
environment:
  - AWS_ACCESS_KEY_ID
  - AWS_SECRET_ACCESS_KEY
```

### Example: Branching Strategy

The last example describes which branches should be considered in some phases (ref. `name`) and which branches should be created in some other phases (ref. `from` and `to`).

```
phases:
  build:
    branches:
      - name: develop
        when: env == "Dev"
      - from: develop
        to: "release/v${VERSION}"
        when: env == "QA"
```

Thoughts?

**Comment by michaelsauter** [comment]
@metmajer I am definitely open to move the branch-to-environment information elsewhere. The `Jenkinsfile` was just the most obvious place to put it at the time. A few things to think about in this context:

- Should the branching model be a component concept, or a project concept? I feel that usually, teams would decide on a branching model across all components ... that said, the branching is "owned" by Git in the end, so somehow belongs to the component.
- Reading a YAML file from Jenkins might be tricky. Right now the shared lib does not depend on approval of any methods, and it would be great to keep it that way. Do you know how easy/hard it is to read that YAML file?
- I don't really get the "Branching Strategy" example. I assume `dev` is something known to the pipeline? But what does QA do when the release branch already exists? Just want to raise that I am not entirely sure what this does/means just by looking at it. The other examples make sense to me, definitely like the "Pipeline phases" suggestion.

**Comment by rattermeyer** [comment]
Hmm. I am also not convinced yet. Currently it seems, that we rebuild something that is already part of a Jenkinsfile (stages, etc).

So lets start what where the Architectural Drivers of the initial solution and see, what other architectural drivers have come on the stage.

We started with the following drivers (not exhaustive)

Maintainability:
* Use as much as possible from the standards as possible (OpenShift / Jenkins / ....)
* Keep as integrated as possible
* Keep effort to maintain base images as low as possible

Flexibility
* Make it easy to adopt to any workflow that a team wants to choose
Understandability
* Make sure, that it can be easily understood where changes have to be made
* (Constraint): Focus on single component flow 

Solution Strategy:
* Use OpenShift Pipeline Build Strategy that employs Jenkins Pipelines
* Jenkins Pipelines as a core concept that are easily understood by developers
* Do not use any specific libraries / code that requires Jenkins script approval (and require changes of the slave base image)

Target audience:
* Programmers (that should be comfortable with Jenkins Pipelines)

Trade-offs:
* Configurations must be programmed in groovy instead of declared in a more declarative fashion
* Limitiation in the available programming constructs / libraries 

Probably you could add newly discovered architectural drivers behind your solution strategy.

**Comment by rattermeyer** [comment]
The proposed changes in Michaels initial post contribute to the architectural drivers

Replacement of Rundeckt with Jenkins --> Maintainability (less different components, standards)
Multiple Quickstarter repos --> Flexibility
Proper Templating --> Maintainability
...
That' why I like the proposoals. Also the drive for more consistency (templates vs tailor files) that also helps understanbility.
We probably need to collect these architectural principals somewhere in the documentation

**Comment by metmajer** [comment]
All, I am not proposing final solutions here. To me, the title of the story is an invitation to challenge the status quo. Don't think that I do not see the hard work everyone on this team has put into this project and, while I am hoping for many things to be changed, I will be happy to be part of this mission and contribute myself as needed.

My personal goal is to find ways to make ODS easier to onboard and use by people who are not engineering experts. I do fully support the design drivers! However, the biggest obstacle to a product's successful adoption in the enterprise has always been *ease of use*. The closest one that @rattermeyer describes is *Flexibility*, but that doesn't quite nail it for me. I'd like to see it less as "Make sure, that it can be easily understood where changes have to be made" and more as "Don't make me think".

@michaelsauter I feel it should be made configurable at the component level, too, but it could be defined and injected at the project level and passed on to the components through the orchestration pipeline as arguments.

For reading YAML files, I have been using the following library that can be loaded from within the Groovy sandboxed Jenkinsfiles even and doesn't cause any hick-ups:

```
@Grab('org.yaml:snakeyaml:1.24')
import org.yaml.snakeyaml.Yaml
```

I have also updated the branching strategy example which hopefully creates more clarity. Again, take my proposals as food for thought and hopefully lively discussions.

**Comment by michaelsauter** [comment]
Thanks a lot for all the discussion! I'm closing this as a lot of what has been discussed in here will make it into release 2.

Everyone who still has concrete open topics after release 2 has been released, please open a new, focused issue.
