### ISSUE TITLE
be-docker-plain quickstarter fails in initial deployment

### ISSUE THREAD

**Issue by tbugfinder** [opendevstack/ods-project-quickstarters#260]
`echo` isn't a background process listening on the configured port, therefore it fails during initial deployment.

https://github.com/opendevstack/ods-project-quickstarters/blob/289e53ea14e6e6e2c297a4685c74225954f65c4f/boilerplates/be-docker-plain/files/docker/Dockerfile#L4

**Comment by metmajer** [comment]
Hey @tbugfinder!

If you use the provided Dockerfile as-is, a container will exit immediately. This is because the Dockerfile is lacking a properly defined [`CMD`](https://docs.docker.com/engine/reference/builder/#cmd) or [`ENTRYPOINT`](https://docs.docker.com/engine/reference/builder/#entrypoint) directive to specify which command to run at container run-time. [`RUN`](https://docs.docker.com/engine/reference/builder/#run) directives, on the other hand, are evaluated solely at image build time.

On a side note, containers typically don't run background processes. At least, that's not what they have been designed for: a container is a hull around exactly one foreground-running process. If you were to fork this process into the background, the container would exit immediately. On the other hand side, it is sometimes desirable to have the foreground-running process be accompanied by other, long-running background processes, e.g., for run-time configuration management and logging. Today, this is not considered good practice, and has resulted in the [Sidecar pattern](https://docs.microsoft.com/en-us/azure/architecture/patterns/sidecar) to augment an application with such additional capabilities.

**Comment by tbugfinder** [comment]
Agreed, my wording wasn't really appropriate.

**Comment by metmajer** [comment]
Nevertheless, the Dockerfile could benefit from some improvements. Here are my suggestions:

- Provide a `CMD ["true"]` to provide something users can start with. Also suggests that `CMD` is generally preferred over `ENTRYPOINT` for the sake of being overridable by the user post-build.
- Reference a consistent image family in the `FROM` clause. While here we reference a `rhel` image from the Red Hat Container Catalog, [be-springboot uses an Alpine-based OpenJDK 8](https://github.com/opendevstack/ods-project-quickstarters/blob/master/boilerplates/be-springboot/files/docker/Dockerfile).

Additionally, since these images are meant to run on OpenShift, we should consider incorporating the basics from [OpenShift's General Container Image Guidelines](https://docs.openshift.com/container-platform/3.9/creating_images/guidelines.html). Otherwise, images will implicitly run under the `root` user, which is disabled by default on OpenShift.

```
RUN chgrp -R 0 /app && \
    chmod -R g=u /app

USER 1001
```

@clemensutschig @michaelsauter @rattermeyer @tjaeschke Thoughts?

**Comment by michaelsauter** [comment]
@metmajer I like your suggestions! Regarding base images, I think Alpine images are a good default choice for running apps.

**Comment by rattermeyer** [comment]
I completely second this. We need to think what the base images are, because we want to support two different scenarios

* Open Source: not all rhel images are free [but might change to some extend](https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image)
* Available support based on OpenShift platform (compared to OKD)

So the options could be

1. use OpenSource base image (like Alpine)
1. use UBI base images where reasonable (because of compliance and support)
1. switch using bc and tailor (as we do for [slave-base](https://github.com/opendevstack/ods-core/blob/master/jenkins/ocp-config/bc.yml)

I would very much prefer 1. and could also live with 2. and would like to avoid 3 (because of maintenance burden)

**Comment by metmajer** [comment]
+1 for using Alpine-based images to start with

**Comment by tbugfinder** [comment]
The initial intent of this quickstarter was support of "vendor" based images.
In that sense the image itself wouldn't really matter.

**Comment by michaelsauter** [comment]
@tbugfinder OK. Still it would be good to be consistent with base images. Besides nothing in ODS itself suggests that this is for vendor-supplied software only, so it might also be used for software for which there is no quickstarter ....

**Comment by rattermeyer** [comment]
hmm. wondering if this quickstarter could be used to implement a secure content workflow, as described [here](https://blog.docker.com/2019/06/a-secure-content-workflow-from-docker-hub-to-dtr/). I would very much appreciate imposing a more secure workflow than pulling any image into the environment.

**Comment by tbugfinder** [comment]
Started WIP:
https://github.com/opendevstack/ods-project-quickstarters/pull/264

There are other be- quickstarters which are based on RHEL images. Howto deal with those?
