### ISSUE TITLE
Add related people to quickstarter readme

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-project-quickstarters#266]
We want to add a note in each quickstarter readme like this:

```
For pull requests and discussion regarding direction, please pull in @abc, @def 
```

Purpose is to have some degree of responsibility for each quickstarter.

Please add yourself to the quickstarter readmes via PRs.

@gerardcl @hugowschneider @oalyman @stitakis @henrjk @akhilsoman @cschweikert @ManuelFeller @m-apsolon @renedupont @rianet @ultrasonicsoft @adyachok @sklingel

**Comment by gerardcl** [comment]
@michaelsauter , shall we tackle #206 here too?

**Comment by michaelsauter** [comment]
@gerardcl No, please just one issue at a time :)

**Comment by gerardcl** [comment]
hi @michaelsauter ! I agree on what issue in a per issue basis hehe but I was referring to that since it is talking about who do we put as a maintainer of the Dockerfiles, at least from a Quickstarter point of view, which is totally aligned with this issue.
But yes! let's tacklet the topic of the maintainer label there!

**Comment by michaelsauter** [comment]
Closing as that has never really happened. We will rework how we address this for release 3.
