### ISSUE TITLE
import of *cd* project creates broken jenkins sa

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-project-quickstarters#325]
upon running import.sh of a *cd project the jenkins SA account is broken - which leads to image pull errors.

utschig@WKS0000627058 MINGW64 /c/code_bix/opendevstack_at_BIX/ods-mro-jenkins-shared-library (feature/add-summary-backup)
$ oc describe sa jenkins
Name:                jenkins
Namespace:           b2p2-cd
Labels:              template=cd-jenkins-persistent-template
Annotations:         serviceaccounts.openshift.io/oauth-redirectreference.jenkins={"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"jenkins"}}
Image pull secrets:  jenkins-dockercfg-wqg8p **(not found)**
Mountable secrets:   jenkins-token-6wkrq **(not found)**
                     jenkins-dockercfg-wqg8p **(not found)**
                     jenkins-token-r422q
Tokens:              jenkins-token-r422q
Events:              <none>

**Comment by clemensutschig** [comment]
@gerardcl  / @hugowschneider - do you still have the log from the import.. I am wondering if oc-apply did some mess here?

**Comment by clemensutschig** [comment]
recreating the SA fixed this (including the annotation)

**Comment by gerardcl** [comment]
apply warning message:
```
Warning: oc apply should be used on resource created by either oc create --save-config or oc apply
```

**Comment by hugowschneider** [comment]
I do not have any logs with me anymore...

**Comment by clemensutschig** [comment]
again . the fix for this is to create the sa before calling oc apply .. a simple "oc create sa jenkins" shoud suffice. do you folks pick thisup?

**Comment by gerardcl** [comment]
yep, on it during today latest on Monday... will also provide patch for deprecation warnings if make sense, first will just test this sa creation

**Comment by clemensutschig** [comment]
I would add `oc create sa jenkins`  (in case project name~ cd) in https://github.com/opendevstack/ods-project-quickstarters/blob/master/ocp-templates/scripts/import_ocp_project_metadata.sh#L457

**Comment by clemensutschig** [comment]
Oc apply afterwards will do the Rest.. and if you want to check it.. do `oc describe sa jenkins` afterwards

**Comment by gerardcl** [comment]
sure! already on a loop with them :) will keep you all posted

**Comment by gerardcl** [comment]
ok... `oc create sa jenkins`  is not the solution, I tested then updating to `oc get --export ...` (instead of `oc export ...`) and to use `oc create --save-config...`... with this change the cloning works and the whole pipeline (build with pulls, pushs,...) but since the rolebindings are not "cloned" (the current script/s do not handle it properly) we get out without having access to the new namespace..

I checked the import script and there is no import that handles properly the migration of rolebindings indeed... is there any reason for that? if there is no reason for that then with just adding this export/import addition will solve the whole issue (and I would say even without requiring the ClusterRole magic creation from that RH solution, at least on a RHD cluster)....

By checking the sa/rolebindings of the new namespace created and comparing from the source one, one can see that there is definitely missing the admin users/groups for example, and that is the reason we do not have access to the newly created one... let's meet on Monday and tackle it together... 🚀

**Comment by gerardcl** [comment]
more explanations:
- oc get --export promotes more information required for a proper later import
- https://github.com/opendevstack/ods-project-quickstarters/blob/6ae39300c49740abf4d62357f465c7f78d7c9bf4/ocp-templates/scripts/import_ocp_project_metadata.sh#L455 does not apply any change since both `OD_OCP_CD_SA_SOURCE` and `OD_OCP_CD_SA_TARGET` are empty. For me this line should be changed to something like indeed:
```
sed -i -e "s|$OD_OCP_SOURCE_NAMESPACE|$OD_OCP_TARGET_NAMESPACE|g" project.yml$tmp_postfix
```
and then run:
```
oc create --save-config -f project.yml$tmp_postfix
```
- what is missing though is a proper import of the Users and its Roles, we could also automate that

proposal:
- discuss if what I am saying makes sense to you all
- if it makes sense, we could make a change, from an export and import point of view, that would be really making a list of users and groups, and its roles and then apply that at import stage (as done for routes, bc, is, services,....).. via `oc policy add-role-to-user`and `oc policy add-role-to-group`

If you already agree I will start implementing such change,

TTY!

**Comment by clemensutschig** [comment]
@gerardcl please Save your Project.. i want to take a look tmrw am with u
