### ISSUE TITLE
Replace upload-templates.sh with tailor 

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-project-quickstarters#38]
Consistency - all oc artifact install thru tailor

**Comment by michaelsauter** [comment]
This would be nice, but to do it properly will take some refactoring. The current approach works, and therefore I would remove this from the 1.0 milestone, and tackle it afterwards. @clemensutschig agreed?

**Comment by clemensutschig** [comment]
removed .. agree :D

**Comment by henrjk** [comment]
`upload_templates.sh` uses `oc apply` to upload templates to the catalog or update already uploaded templates.  In my understanding this will not actually instantiate the template and thus not create the actual resources.
On the other hand in my understanding a `tailor update` actually processes a template and would create/update the resources of that template as needed. 

Currently for example create-project.sh does the template instantiation.
[ods-project-quickstarters/create-projects.sh at 1.0.x · opendevstack/ods-project-quickstarters](https://github.com/opendevstack/ods-project-quickstarters/blob/1.0.x/ocp-templates/scripts/create-projects.sh#L105)

It is not clear to how this should change. One possibility could be that the templates are not uploaded at all and instead instantiated/applied directly from the file system. 

@michaelsauter can you clarify what is needed here and also what refactoring you have in mind?

**Comment by michaelsauter** [comment]
@henrjk Right. My thinking was to not upload templates at all. The issue with uploaded templates is that a) one can forget to upload and b) it prevents branching. A developer cannot try a change to the template without potentially breaking everyone else.

What I would like to see is that the templates are in the repository, and that the Rundeck jobs use those templates in conjunction with Tailor to instantiate them.

**Comment by henrjk** [comment]
The rundeck jobs currently create a container to run oc commands for expanding the previously uploaded templates.

One approach would be to instead have a container which has oc, tailor and the appropriate ocp_config for the quickstarter and then execute the tailor command(s) for example for create-rshiny-app. Does this make sense? If so, is there already a tailor container somewhere?

Should the template for cd//secrets still be uploaded, so that there is a central place from which the project secret configs are created in create-projects.sh (not changing that from how it is done today) or would we rather do away with these templates as well and have the secrets be passed into the rundeck script as parameters by the user?

**Comment by michaelsauter** [comment]
@henrjk Yes, I think this would be the right thing to do. We already install Tailor in the slave base, see https://github.com/opendevstack/ods-core/blob/master/jenkins/slave-base/Dockerfile.rhel7#L65-L70.

I'm not sure why you want to keep the secrets uploaded, maybe you can explain a bit more? Putting the secrets into the repos is not great, but then again we already have them committed in the config repo so its not worse as before ...

**Comment by henrjk** [comment]
@michaelsauter Regarding uploaded secrets, I was thinking that perhaps it would be an advantage to have a central place to update so that future projects will use the 'latest' credentials. 

However I would rather have a different cd_user identity with its own credentials for each project. Even if that would be the right thing to do perhaps this should be a handled in a separate issue.

**Comment by michaelsauter** [comment]
@henrjk Correct, see #134.

I actually think having the secrets pulled from the repo is "safer" because you cannot forget to update the template in OCP.

**Comment by clemensutschig** [comment]
@henrjk - do you think this is a 1.1. thing .. or move out to 1.2? (@michaelsauter  fya)

**Comment by henrjk** [comment]
If I get some cycles within the next 2 weeks I might get it to a review worthy state. From my perspective it is not crucial to have it in 1.1 and could instead move it 1.2.0.

**Comment by henrjk** [comment]
At the moment I am looking at the rshiny templates. The related create/delete script are referencing a template named `cd/component-pipeline` which I have only found in our OpenShift environment but not in the source code here. 

https://github.com/opendevstack/ods-project-quickstarters/blob/0388907de67e3e72617162719180389b5237e77a/ocp-templates/scripts/create-rshiny-app.sh#L53

Where is this created?

**Comment by michaelsauter** [comment]
Not sure but I think we removed those and also build them via Jenkins now. At least we should.

**Comment by clemensutschig** [comment]
But that means the job fails.. ;-( another regression

Michael Sauter <notifications@github.com> schrieb am Fr., 10. Mai 2019,
17:45:

**Comment by henrjk** [comment]
The wip changes I tested so far are in the scripts and by creating the needed templates for tailor in a new directory called ocp-templates/ocp-config. 

The next step is to integrate these so that the rundeck jobs continue to work correctly.

I'd like to test this end to end, meaning from by invoking them using the provisioning app and ensure these run correctly.

If I had a wish, I'd like to be able to be able to instantiate easily for testing purposes:
- A provision app which uses a private rundeck instance. This part should be easily doable as the provisioning app is already in openshift and one could. 
- A private rundeck instance which would be populated from the branch origin/feature-wip-branch
I assume one cannot do this easily at the moment, but perhaps I am wrong?

An alternative is to duplicate rundeck jobs including their references and change them so they check out the feature branch and reference the duplicated versions.  However this can get tedious and it looks error prone to me.

Here is an idea to mitigate this: 
1. Introducing a new option for all rundeck jobs:

```yml
options:
  - description: Optional feature branch for testing (defaults to origin/production)
    name: branch
    required: true
    value: origin/production
```  

2. When rundeck job reference other rundeck jobs they are changed so that they pass on this 

3. All statements in the jobs who currently check out origin/production would instead check out the specified branch

For example in

```yml
    - description: clone oc script project
      exec: >-
          cd /tmp/rundeck_${job.id}_${job.execid} &&
          git clone ${globals.bitbucket_sshhost}/opendevstack/ods-project-quickstarters.git &&
          cd ods-project-quickstarters &&
          git checkout origin/production
```  

the last line would become

```yml
          git checkout ${option.branch}
```  

Now one could simply specify the feature branch, although one would still have to update changed rundeck scripts manually as before.

@michaelsauter, @clemensutschig, @hugowschneider, @gerardcl does this make sense?

**Comment by michaelsauter** [comment]
@henrjk Sure, that does make sense, but it also sound like a lot of work. Especially since I'm not sure investing in Rundeck is worth it. My take on Rundeck is that it is a terrible system to work with (for many reasons). AFAIK the common understanding is to get rid of it rather sooner than later (and replace with Jenkins pipelines).

I would suggest to just duplicate the jobs and edit them ... I see how this is error-prone, but the suggested alternative also sounds like many things can go wrong :)

**Comment by henrjk** [comment]
Initially my solution was basically a refactoring of existing scripts. While this was working in a private branch for me @michaelsauter introduced the idea to have the shared libraries jenkins build look at the openshift folder and if found invoke tailor using these (see https://github.com/opendevstack/ods-jenkins-shared-library/pull/85)

So instead of invoking tailor during rundeck jobs the rundeck job create openshift yaml files, which are then processed during the build. 

First tests have now worked for me. Having the PR above available would simplify further testing a lot. 

Some other notes about the direction I am going: 
- move where possible code out of rundeck into scripts.
- keep create-projects with refactored as there is no jenkins yet.  
- exit scripts when invoked with unknown parameters
- use label app:<PROJECT>-<COMPONENT> and template=<originating template> to demarcate the OpenShift resources. These labels can be used to delete the components. 
- remove delete-component.sh and delete-rshiny.sh as we want to have people do this manually by deleting resources by name or with the selectors introduced above.
- bash scripts should fail on error (set -ux)

**Comment by henrjk** [comment]
We reverted direction and resurrected the more basic approach as outline in the comment from June 7. See PR #310 for additional details. 

The reason for the change of direction is #283 which changes how openshift resources will be managed/created in 2.0 and we did not want to introduce yet another approach in 1.2 as envisioned in mentioned comment.
