### ISSUE TITLE
Experiment with different quickstarter structure

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-project-quickstarters#68]
I think that the whole repo should be structured differently than it is right now. A lot of the repo should be moved to `ods-core`, and what is left should be really decoupled from opendevstack. In addition, users should have an easy way to add their own quickstarters.

To make some progress in this direction, I want to try out the following:

Create a new Rundeck job that is usable for all quickstarters. This Rundeck job requires a `quickstarter_repository`, a `boilerplate_path` and a `ocp_template_path` param (the last two being relative paths inside the repo). Since the provisioning app cannot set this at the moment, I will - for the sake of the experiment - not integrate this Rundeck job with the provisioning app.

This new Rundeck job will execute a predefined set of steps, as sketched below:

1. Clone the `quickstarter_repository`
2. Create a new folder and set correct permissions on it
3. Initialise (which is either the `init.sh` in `boilerplate_path` or, if that does not exist, a default one provided by `ods-core/quickstarters-steps/init.sh`)
4. Generate (which is either the `generate.sh` in `boilerplate_path` or, if that does not exist, a default one provided by `ods-core/quickstarters-steps/generate.sh`)
5. Copy files (which copies all files in `boilerplate_path/files` to the new folder
6. Render `Jenkinsfile` and `sonar-project.properties` if present
7. Process (which is either the `process.sh` in `boilerplate_path` or, if that does not exist, a default one provided by `ods-core/quickstarters-steps/process.sh`)
8. Create OCP resources (by applying the templates in `ocp_template_path`)
9. Initialise the git repository and push it

Each file such as `init.sh`, `generate.sh`, etc. will be called with a predefined set of environment variables (to ease writing custom scripts).

Advantages:
* Quickstarters can be sourced from multiple repos, allowing orgs to point to their own
* No Rundeck job needs to be created when new quickstarters are created. As a consequence, the Rundeck config can be moved to `ods-core`, along with all the default scripts and project templates etc.

When I have some time, I will experiment with an example Rundeck job that does this ...

FYI @rattermeyer @tjaeschke @clemensutschig @stitakis

**Comment by rattermeyer** [comment]
The proposal sounds good to me. The de-coupling really makes sense.
The convention makes sense with respect to what we currently have learned about different project flavours.

**Comment by clemensutschig** [comment]
massively related to opendevstack/ods-provisioning-app#98

my thought would be 

1. to have the "main" CD project contain 1 master pipeline to create/delete a project - largely reusing what's done in
https://github.com/opendevstack/ods-project-quickstarters/blob/master/rundeck-jobs/openshift/create-projects.yaml - that requires a jenkins instance in CD - including a SA with self provisioner rights

2. have a pipeline "provision new components" in every `project *-cd` project - in order to piggy back on the `*-cd jenkins SA`'s rights .. which would allow you to pass the quickstarter name, or a github.. location which contains a jenkins file to provision quickstarter specifics. 

The open question for me is where to get the quickstarter list from ... (today it's a query against rundeck, namely in
https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/java/org/opendevstack/provision/services/RundeckAdapter.java#L226 which uses the group configured in https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/resources/application.properties#L74

The easiest way I guess is to create pipelines with a naming convention e.g. Quickstarter-* in the main CD project that the prov app could read... (oc get pipelines | grep ... ) or you configure it in the prov app - with paths?

@gerardcl  / @michaelsauter  @stitakis  - thoughts?

**Comment by michaelsauter** [comment]
Very cool!

As dicussed, the quickstarter list needs to be known in some form or other by the provisioning app. However, this is something we want anyway, in order to point to e.g. private quickstarter repos.

The provisioning app would then give the Git repo and the Jenkinsfile path to the webhook proxy, which would create a pipeline, and run the steps defined in the Jenkinsfile. The prov-app also needs to pass the component name (to create the OCP resources and the BitBucket repo), and this is doable via args in the Jenkins strategy (webhook proxy needs to be extended, but is a simple addition).

**Comment by stitakis** [comment]
Excellent! 
The prov app could get the configuration of quickstarters location, etc... from:
- from config file (ie. json file) added to the prov-app project as mentioned above
- or from default config file located in a default git repo url
- or something similar :-)

**Comment by michaelsauter** [comment]
@kiwo Assigning you on this since you are working on it - even if the implementation might slightly differ from what was in here originally.
